# This is a basic workflow that is manually triggered

name: CI with Java and Gradle

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Setup java
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    # Checks-out our code
    - name: Checkout out code   
      uses: actions/checkout@v2
    
    # Make gradlew executable
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
      
    # Do a build scan
    - name: Build with Gradle
      run: ./gradlew build --scan
      
    
      
    # Generate  Javadoc
    - name: Generate Javadoc
      run: ./gradlew aggregateJavadocs
      
    
      
    
